### ISSUE TITLE
unassigned projects not possible to assign when not included in query

### ISSUE THREAD

**Issue by kingkastle** [udacity/reviewer-dashboard-feedback#42]
When there are unassigned projects that are not queried, these are not available:

[See this video showing an example](https://drive.google.com/open?id=1wLEwwYtHkT3DTTTBIGsZ7nIRN_6izY44)

**Comment by amandaraney** [comment]
Thanks for flagging, I took a look at the video, that is expected behavior. In the queue options, you are choosing what projects you would like to have assigned to you. If you don't select a project, we won't provide a submission to you. When you switch to the old dashboard, the three projects you show as available are not toggled "on" for selection in your queue options.
